### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kyleburton** [paraseba/faker#2]
Hi, I see that this library hasn't been touched in quite a while.  I was about to fork it to update it to work with Clojure 1.7 - but I see that there is no license in the repository.  Have you chosen a license for this code?  Can you add one to the repository?

**Comment by paraseba** [comment]
Hi Kyle,

  Thanks for noticing. I'll do that today, it's going to be Eclipse

**Comment by paraseba** [comment]
Thanks Kyle. Feel free to submit PRs.
